#! /bin/sh

# display positions
xrandr --output DisplayPort-3 --gamma 1.0:0.95:0.85 --brightness 0.70 --primary --mode 1920x1080 --pos 0x0 &
xrandr --output DisplayPort-4 --gamma 1.0:0.95:0.85 --brightness 0.70 --mode 1920x1080 --pos 1920x0 &
# display bright and gamma
# xrandr --output DisplayPort-3 --gamma 1.0:0.95:0.85 --brightness 0.70 &
# xrandr --output DisplayPort-4 --gamma 1.0:0.95:0.85 --brightness 0.70 &

lxpolkit &
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x dunst > /dev/null || dunst -conf ~/.config/dunst/dunstrc & 
nitrogen --restore &
pgrep -x picom > /dev/null || picom &
xsetroot -cursor_name left_ptr &
numlockx on &

if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    bspc monitor $m -d 1 2 3 4
  done
fi

~/.config/polybar/polybar.launch.sh &
~/.config/bspwm/scripts/monitor.sh &

bspc config border_width         1
bspc config window_gap           2

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config focused_border_color      '#8ec07c'
bspc config normal_border_color       '#282828'
bspc config active_border_color       '#3c3836'

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config focus_by_distance     true

bspc config automatic_scheme spiral
bspc config initial_polarity first_child
bspc config removal_adjustment true

# how much of the screen the "master" takes by default

bspc rule -a \* center=on
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#bspc rule -a "WatchList" state=floating
#bspc rule -a "Console" state=floating
#bspc rule -a "WaveWindow" state=floating
bspc rule -a "Dialog" state=floating center=on
bspc rule -a "Toplevel" state=floating center=on
bspc rule -a "Terminator Preferences" state=floating center=on
